"""Builds a Windows .exe for the desktop GUI using PyInstaller.

Usage:
    python scripts/build_windows.py               # full build -> dist/OfficeAutomationPlatform/
    python scripts/build_windows.py --smoke-test  # validates PyInstaller + entrypoint import only

A full build must run on Windows (PyInstaller does not cross-compile).

After a full build, wrap it into a proper installer:
    1. Install Inno Setup: https://jrsoftware.org/isinfo.php
    2. iscc packaging\\windows\\installer.iss
    3. dist\\installer\\OfficeAutomationPlatform-Setup-<version>.exe

The build embeds Windows version-resource metadata from
packaging/windows/version_info.txt (visible in the .exe's file Properties),
and bundles config/ + alembic/ + alembic.ini + .env.example so the
installed application has everything docs/INSTALLATION.md's setup steps
need without hunting for the source repository.

An icon is used if present at packaging/windows/icon.ico - this repository
does not ship one (no binary assets are generated by this codebase); add
your office's icon there before building for a polished result. The build
proceeds without one otherwise.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENTRYPOINT = REPO_ROOT / "app" / "gui" / "main.py"
ICON_PATH = REPO_ROOT / "packaging" / "windows" / "icon.ico"
VERSION_FILE = REPO_ROOT / "packaging" / "windows" / "version_info.txt"


def smoke_test() -> None:
    """Verify PyInstaller is importable and the GUI entrypoint module parses,
    without invoking a full (slow) native build. Used by CI on every OS."""
    import importlib.util

    spec = importlib.util.find_spec("PyInstaller")
    if spec is None:
        print("PyInstaller not installed - run `pip install pyinstaller`", file=sys.stderr)
        raise SystemExit(1)
    compile(ENTRYPOINT.read_text(encoding="utf-8"), str(ENTRYPOINT), "exec")
    print("Smoke test passed: PyInstaller available, GUI entrypoint compiles.")


def full_build() -> None:
    args = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--windowed",
        "--name",
        "OfficeAutomationPlatform",
        "--add-data",
        f"{REPO_ROOT / 'config'};config",
        "--add-data",
        f"{REPO_ROOT / 'alembic'};alembic",
        "--add-data",
        f"{REPO_ROOT / 'alembic.ini'};.",
    ]

    if VERSION_FILE.exists():
        args += ["--version-file", str(VERSION_FILE)]
    else:
        print(f"Note: {VERSION_FILE} not found - building without version metadata.")

    if ICON_PATH.exists():
        args += ["--icon", str(ICON_PATH)]
    else:
        print(f"Note: {ICON_PATH} not found - building without a custom icon.")

    args.append(str(ENTRYPOINT))

    subprocess.check_call(args, cwd=REPO_ROOT)
    print("Build complete: dist/OfficeAutomationPlatform/OfficeAutomationPlatform.exe")
    print("Next: wrap it into an installer with packaging/windows/installer.iss (see this script's docstring).")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke-test", action="store_true")
    args = parser.parse_args()

    if args.smoke_test:
        smoke_test()
    else:
        full_build()


if __name__ == "__main__":
    main()
