"""Builds a macOS .app bundle for the desktop GUI using PyInstaller.

Usage:
    python scripts/build_macos.py               # full build -> dist/OfficeAutomationPlatform.app
    python scripts/build_macos.py --smoke-test   # validates PyInstaller + entrypoint import only

A full build must run on macOS (PyInstaller does not cross-compile).

After a full build, package it into a distributable .dmg:
    bash packaging/macos/create_dmg.sh

Code signing/notarization for distribution outside your own machine
requires an Apple Developer ID certificate - see the header comment in
packaging/macos/create_dmg.sh for the exact `codesign`/`notarytool`
commands once you have one. Gatekeeper will otherwise block the .app on
any Mac other than the one that built it.

The build bundles config/ + alembic/ + alembic.ini + .env.example inside
the .app's Resources so the installed application has everything
docs/INSTALLATION.md's setup steps need.

An icon is used if present at packaging/macos/icon.icns - this repository
does not ship one (no binary assets are generated by this codebase); add
your office's icon there before building for a polished result. The build
proceeds without one otherwise.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENTRYPOINT = REPO_ROOT / "app" / "gui" / "main.py"
ICON_PATH = REPO_ROOT / "packaging" / "macos" / "icon.icns"


def smoke_test() -> None:
    import importlib.util

    spec = importlib.util.find_spec("PyInstaller")
    if spec is None:
        print("PyInstaller not installed - run `pip install pyinstaller`", file=sys.stderr)
        raise SystemExit(1)
    compile(ENTRYPOINT.read_text(encoding="utf-8"), str(ENTRYPOINT), "exec")
    print("Smoke test passed: PyInstaller available, GUI entrypoint compiles.")


def full_build() -> None:
    args = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--windowed",
        "--name",
        "OfficeAutomationPlatform",
        "--add-data",
        f"{REPO_ROOT / 'config'}:config",
        "--add-data",
        f"{REPO_ROOT / 'alembic'}:alembic",
        "--add-data",
        f"{REPO_ROOT / 'alembic.ini'}:.",
    ]

    if ICON_PATH.exists():
        args += ["--icon", str(ICON_PATH)]
    else:
        print(f"Note: {ICON_PATH} not found - building without a custom icon.")

    args.append(str(ENTRYPOINT))

    subprocess.check_call(args, cwd=REPO_ROOT)
    print("Build complete: dist/OfficeAutomationPlatform.app")
    print("Next: bash packaging/macos/create_dmg.sh to produce a distributable .dmg.")
    print("Reminder: unsigned. For distribution, codesign + notarize with an Apple Developer ID.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke-test", action="store_true")
    args = parser.parse_args()

    if args.smoke_test:
        smoke_test()
    else:
        full_build()


if __name__ == "__main__":
    main()
